### ISSUE TITLE
Should `memory.init`/`drop` of active segments be a validation error?

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/bulk-memory-operations#107]
Presumably they could be validation errors, but the DataCount section doesn't have enough information?

Was a bitfield considered rather than a single number for the DataCount section?

**Comment by binji** [comment]
There was a long discussion about this here: https://github.com/WebAssembly/bulk-memory-operations/issues/27, starting from [this comment](https://github.com/WebAssembly/bulk-memory-operations/issues/27#issuecomment-421379736).

Luke explains the rationale in a following comment: "although taking into account what @conrad-watt's pov, the "active/passive" distinction goes away at runtime; there are simply "has the segment already been dropped", with active segments having been desugared into table.init;table.drop expressions executed before the start function"

**Comment by sbc100** [comment]
ok sgtm
