### ISSUE TITLE
Meaning of out-of-range zero-length 'memory.fill' / 'memory.copy'

### ISSUE THREAD

**Issue by julian-seward1** [WebAssembly/bulk-memory-operations#11]
What should happen when memory.fill/.copy are requested to process zero bytes, but the destination and/or source offsets are out of range?  Should there be an out-of-range exception?  Or should the operations be no-ops?

I'd vote for throwing an exception, on safety/correctness grounds.

**Comment by jfbastien** [comment]
I would advocate for the same behavior as for data segments. There was pretty extensive discussion here: https://github.com/WebAssembly/design/issues/897

**Comment by rossberg** [comment]
@jfbastien, seconded. That would imply that these instructions trap when either source or destination end offset is out of bounds. That would match @julian-seward1's preference as well.
