### ISSUE TITLE
Tests of memory.init in the absence of DataCount section

### ISSUE THREAD

**Issue by sbc100** [WebAssembly/bulk-memory-operations#125]
I notices that v8 fails validation in this case but wabt doesn't.  Assuming that wabt passes all the spec tests are we missing a test here?

See https://github.com/WebAssembly/wabt/issues/1176

**Comment by eqrion** [comment]
It looks like there is indeed a test for [this](https://github.com/WebAssembly/bulk-memory-operations/blob/24b0882649166e51296bae944853160c7f93c28c/test/core/binary.wast#L682) already. Or is that covering a different case than yours?

**Comment by sbc100** [comment]
Ah, it looks like a bug in wabt.  The tests are passing because the intepreter checks for this error case, not the validator code (so wasm-validate doesn't fail).
