### ISSUE TITLE
Repo website link is broken (404)

### ISSUE THREAD

**Issue by AndrewScheidecker** [WebAssembly/bulk-memory-operations#135]
This repo has this link as its website:
https://webassembly.github.io/bulk-memory-operations/

But that link is a 404.

**Comment by binji** [comment]
I've set this up to use Travis to build the docs, thanks to @rossberg's excellent howto. :-)

**Comment by rossberg** [comment]
FWIW, if you want to see the fully complete spec for table instructions you'll need to look at the [rendered spec for reference types](https://webassembly.github.io/reference-types/), which is based on this one. As mentioned [here](https://github.com/WebAssembly/bulk-memory-operations/issues/132#issuecomment-575250095), both semantics are mutually dependent on each other for technical reasons, so some pieces are missing here.
