### ISSUE TITLE
Validation error or parse error when data count section value does not match data section count

### ISSUE THREAD

**Issue by rianhunter** [WebAssembly/bulk-memory-operations#142]
In the Overview.md file it claims it is a validation error if the value in the data count section does not match the number of datas in the data section. In the test cases, e.g. binary.wast, the it is implied to be a parse error. Which is it?

Some basic history digging shows that the statement in Overview.md is from 2018-11-29, while the test case is from 2019. My current assumption is that it should be a parse error based on this but just thought I'd raise the issue here.

**Comment by binji** [comment]
Yeah, it should be a malformed binary. I'll update the overview.
