### ISSUE TITLE
Import/export passive segments?

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#15]
@rossberg mentioned this [here](https://github.com/WebAssembly/bulk-memory-operations/pull/12#discussion_r187429452). Have we discussed importing and exporting passive data and element segments?

Perhaps this would be useful for dynamic linking, though I'm not quite sure how.

**Comment by rossberg** [comment]
One use case could e.g. be the ability to create a module that provides a specific set of string constants as data segments. Then those would be reusable without also having to share a memory or even a memory management policy.

**Comment by lukewagner** [comment]
It sounds possible, but it's not quite a trivial addition (e.g., a new JS API object, probably needing accessors for the contents of the segment), so it'd be nice to have more of a clear need for it.  Also, once we have multi-memory/table, one could achieve the "exported constants without memory management policy" use case by exporting memories/tables (initialized by active non-exported data/elem segments), or even just globals (allowing each one to be named).
