### ISSUE TITLE
Clarify ref.null binary encoding

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#152]
The binary encoding document currently uses `0xD0 0x70`, but it would be clearer to use `elemtype` for this: https://github.com/WebAssembly/bulk-memory-operations/blob/master/document/core/binary/modules.rst#element-section

This is called `reftype` in the reference types proposal, which doesn't exist here.

(reported by @rreverser)

**Comment by rossberg** [comment]
Clarified in reftypes spec.
