### ISSUE TITLE
Incompatibility with long LEB128 form from the core spec

### ISSUE THREAD

**Issue by RReverser** [WebAssembly/bulk-memory-operations#153]
While implementing bulk memory proposal in my parser, I've noticed regressions in some core spec tests. In particular these two are very representative: https://github.com/WebAssembly/bulk-memory-operations/blob/66d90a7de541a9954af09cb9777f20cc0bd8bbe1/test/core/binary-leb128.wast#L24-L39

Here, a `0` table index (the only one allowed previously) is encoded in a suboptimal form of `0x80 0x00`.

The new layout used by this proposal relies on the table index previously being always zero and encoded as `0x00`, and assigns a different meaning to byte at the same position as `0x80` and expects it to be one of the following values:

![image](https://user-images.githubusercontent.com/557590/83692451-ec628a80-a5eb-11ea-9e0e-9e61604420ae.png)

![image](https://user-images.githubusercontent.com/557590/83692461-f5ebf280-a5eb-11ea-9d10-72599a79538e.png)

Such long form is likely not something used by implementations in the wild, but it might be worth double-checking and either supporting such long form too, or at least making an explicit decision about this backward-incompatible binary representation change and removing (?) corresponding tests.

**Comment by gahaas** [comment]
I saw and fixed this issue already in the reference-type proposal. I guess we should also apply the fix here. I created a PR for that.

**Comment by RReverser** [comment]
@gahaas Note that the test above (for data section) exhibits the same problem, as well as 2 more other tests which previously used long form of zero.

**Comment by RReverser** [comment]
Just looked up, these are the other 2 tests incompatible with new layout (aside from 2 above): https://github.com/WebAssembly/bulk-memory-operations/blob/66d90a7de541a9954af09cb9777f20cc0bd8bbe1/test/core/binary.wast#L118-L136

**Comment by RReverser** [comment]
@binji @gahaas Is this going to be resolved in one way or another before moving to stage 4? Seems dangerous from backward compatibility PoV.

**Comment by binji** [comment]
I doubt the long form is used anywhere (it would only happen if someone did it manually), so the backward compatibility risk seems relatively low. But you're right that it would be good to mention and remove tests.

**Comment by RReverser** [comment]
> it would only happen if someone did it manually

It could in theory also happen if an encoder used a 5-byte-padded LEB128 form to start with (like e.g. LLVM does at initial stage), but then didn't optimise it away in post-processing.

**Comment by binji** [comment]
Perhaps, though generally tools only do that for LEB128 values that represent a count/size that needs to be fixed-up.

**Comment by RReverser** [comment]
I assumed that index encoding shares same routines as count/size?

**Comment by binji** [comment]
Binaryen has different functions for fixed- and variable-length LEB128: https://github.com/WebAssembly/binaryen/blob/master/src/wasm-binary.h#L73-L104
So does wabt: https://github.com/WebAssembly/wabt/blob/master/src/leb128.cc#L49-L65

Maybe LLVM does it differently?

**Comment by tlively** [comment]
LLVM also can do it both ways: https://github.com/llvm/llvm-project/blob/master/llvm/include/llvm/Support/LEB128.h

It doesn't look like lld uses any padding when emitting the table index:

 - https://github.com/llvm/llvm-project/blob/932f0276ea29fd58e1a07947e302f3ca9b54e61a/lld/wasm/OutputSections.cpp#L148, 
 - https://github.com/llvm/llvm-project/blob/932f0276ea29fd58e1a07947e302f3ca9b54e61a/lld/wasm/WriterUtils.cpp#L70-L73

**Comment by RReverser** [comment]
Thanks for checking! I guess if both Binaryen and LLVM don't do this, we should be on safe-ish side as that covers most toolchains.

> But you're right that it would be good to mention and remove tests.

Let's just do this then (test removal and explicit documentation).

**Comment by rossberg** [comment]
I believe this was resolved.
