### ISSUE TITLE
Identifiers for passive segments

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/bulk-memory-operations#159]
From the example in the README:

``` wat
(memory 1)
(data (i32.const 0) "hello")   ;; data segment 0, is active so always copied
(data "goodbye")               ;; data segment 1, is passive
```

The code example goes on to use the `memory.init` instruction, which refers to data segment 1 using its explicit index (`1`).

Given that we can assign identifiers to memories and tables, it seems reasonable to also permit this with passive segments, as they can be referenced (like memories and tables, and unlike active segments).

**Comment by 7ombie** [comment]
Just a quick question... Do segments use the same indexspace, or is there one space for memory segments and another for table segments?

**Comment by martianboy** [comment]
@7ombie Data segments and element segments live in separate index spaces, in the same way that memories and tables do.

**Comment by 7ombie** [comment]
Thank you, @martianboy. I was hoping that was the case.

**Comment by rossberg** [comment]
Is your question about the text format? If so, that already allows binding symbolic identifiers for elem and data segments, see e.g. [these](https://github.com/WebAssembly/spec/blob/master/test/core/elem.wast) [tests](https://github.com/WebAssembly/spec/blob/master/test/core/data.wast).

**Comment by 7ombie** [comment]
Thank you, @rossberg. Yep - this is specifically about the text format.

Sorry. I was mainly relying on [`Overview.md`][1], and trying to find extra information from discussions in old issues and the spec (which I still find quite cryptic in places).

People often refer new users to the tests, but they do not include any documentation, so they're actually very little help to anyone trying to learn WebAssembly. For example:

``` wat
;; Syntax

(module
  (memory $m 1)
  (data (i32.const 0))
  (data (i32.const 1) "a" "" "bcd")
  (data (offset (i32.const 0)))
  (data (offset (i32.const 0)) "" "a" "bc" "")
  (data (memory 0) (i32.const 0))
  (data (memory 0x0) (i32.const 1) "a" "" "bcd")
  (data (memory 0x000) (offset (i32.const 0)))
  (data (memory 0) (offset (i32.const 0)) "" "a" "bc" "")
  (data (memory $m) (i32.const 0))
  (data (memory $m) (i32.const 1) "a" "" "bcd")
  (data (memory $m) (offset (i32.const 0)))
  (data (memory $m) (offset (i32.const 0)) "" "a" "bc" "")
  (data $d1 (i32.const 0))
  (data $d2 (i32.const 1) "a" "" "bcd")
  (data $d3 (offset (i32.const 0)))
  (data $d4 (offset (i32.const 0)) "" "a" "bc" "")
  (data $d5 (memory 0) (i32.const 0))
  (data $d6 (memory 0x0) (i32.const 1) "a" "" "bcd")
  (data $d7 (memory 0x000) (offset (i32.const 0)))
  (data $d8 (memory 0) (offset (i32.const 0)) "" "a" "bc" "")
  (data $d9 (memory $m) (i32.const 0))
  (data $d10 (memory $m) (i32.const 1) "a" "" "bcd")
  (data $d11 (memory $m) (offset (i32.const 0)))
  (data $d12 (memory $m) (offset (i32.const 0)) "" "a" "bc" "")
)
```

I understand that you're trying to be helpful, and am genuinely grateful to you for that. I'm just making the general point that WebAssembly relies on the tests as documentation, even though the tests are very poorly documented. It's frustrating, though I understand that you can only personally point me to what is there.

[1]: https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md

**Comment by rossberg** [comment]
Yes, I understand that there is a lack of documentation for new features like this. Note that it just landed in the main draft a few weeks ago. I hope such documentation will pop up in due time somewhere (bear in mind that neither the proposals nor the spec are intended as documentation for a general audience).

**Comment by 7ombie** [comment]
@rossberg - all fair points. Thanks again. It's kind of you to help me out.
