### ISSUE TITLE
Indexing any passive segments ahead of active segments, so indices are more intuitive.

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/bulk-memory-operations#160]
Users need to reference passive segments (by index), but the active segments are dropped at initialization, and are basically never referenced by the user.

In #159, I asked for support for assigning identifiers to passive segments, but even with identifiers, it would still be more intuitive if all of the passive segments were indexed before any active segments (at least when compiling the text format).

Is it possible to change this at this stage? Existing code contains references to explicit segment indices that this would change the value of, but I don't know if the text format can be changed like that??

**Comment by tlively** [comment]
No, this proposal has been standardized and cannot be changed any more without breaking real world code (or tests, in the case of the text format).

**Comment by 7ombie** [comment]
Sorry, @tlively. I hadn't realized how far this had gone when I started bikeshedding.

This feature could still be added, but to tools like `wat2wasm`, with a flag. You're correct though, there's no room for this change in the spec. Sorry for the noise.
