### ISSUE TITLE
[Support] Some legal grammar seems to be omitted by the official spec.

### ISSUE THREAD

**Issue by 7ombie** [WebAssembly/bulk-memory-operations#161]
I was trying to understand the code in [the `data` tests][1], and couldn't find any way to map some of it to [the grammar in the spec][2]. This is the simplest example:

``` wat
(data (i32.const 0))
```

The spec offers two choices:

+ Active segments: ‘(’ ‘𝚍𝚊𝚝𝚊’  𝚒𝚍?  𝑥:𝚖𝚎𝚖𝚞𝚜𝚎<sub>𝐼</sub>  ‘(’ ‘𝚘𝚏𝚏𝚜𝚎𝚝’  𝑒:𝚎𝚡𝚙𝚛<sub>𝐼</sub> ‘)’  𝑏∗:𝚍𝚊𝚝𝚊𝚜𝚝𝚛𝚒𝚗𝚐 ‘)’
+ Passive segments: ‘(’ ‘𝚍𝚊𝚝𝚊’  𝚒𝚍?  𝑏∗:𝚍𝚊𝚝𝚊𝚜𝚝𝚛𝚒𝚗𝚐 ‘)’

The active segment grammar has a required *offset* expression, but the example code does not include an offset. The passive segment grammar cannot contain the `(i32.const 0)` expression, as it can only contain an optional identifier and zero or more datastrings.

Is `(data (i32.const 0))` active or passive, and what does the `(i32.const 0)` part mean?

The *memuse* (𝑥:𝚖𝚎𝚖𝚞𝚜𝚎<sub>𝐼</sub>) and the offset (‘𝚘𝚏𝚏𝚜𝚎𝚝’  𝑒:𝚎𝚡𝚙𝚛<sub>𝐼</sub>) in the active segment grammar each have a little, subscript *I* after them, which I cannot find any explanation for anywhere in the spec. What does it mean?

I also thought the *memuse* was optional (defaulting to `0`), but it appears to be required in the spec. Could somebody please clarify that?

Sorry for all the questions. I really am trying to figure things out before asking for help.

[1]: https://github.com/WebAssembly/spec/blob/master/test/core/data.wast
[2]: https://webassembly.github.io/spec/core/text/modules.html#data-segments

**Comment by martianboy** [comment]
@7ombie Take a look at the Abbreviations section at the end of the Data Segments section. According to that, `(i32.const 0)` is equivalent to `(offset (i32.const 0))`. Also for `memuse`, according to the abbreviations specifying nothing means `(memory 0)`. The same rules and abbreviations are also used for tables and element segments.

**Comment by 7ombie** [comment]
Ahh. Sorry. I don't know how I missed that. I made a point of checking I hadn't missed anything too. Thank you for taking the time, @martianboy. I get it now.
