### ISSUE TITLE
[Proposal] memory.compare/memory.comp

### ISSUE THREAD

**Issue by MaxGraey** [WebAssembly/bulk-memory-operations#21]
Bulk memory comparison is very useful especially for string's comparison and efficient implementation as well as other bulk memory operations strictly depend on target platform.
Behave same as `std::memcmp` in C/C++.
@binji WDYT?

**Comment by binji** [comment]
It's an interesting idea, though I'm not sure it's nearly as common as memcpy/memset. It'd be useful to gather some data showing where it could be used and the expected performance improvement from making it an intrinsic.

**Comment by MaxGraey** [comment]
As I mentioned it pretty useful for string operations like compare two strings ("==", "!=", ">", "<") and especially sensitive when we sorting of bunch of string arrays.

In different platform this implemented different. for example:
* [memcmp for ARM by Apple](https://opensource.apple.com/source/Libc/Libc-825.25/arm/string/memcmp.s.auto.html)
* [memcmp in GCC](https://github.com/gcc-mirror/gcc/blob/master/libiberty/memcmp.c)
* [memcmp with SSE2 intrinsics](https://gist.github.com/karthick18/1361842)

**Comment by rossberg** [comment]
While I cannot judge the general usefulness of this feature, I'd like to point out that using byte-wise comparison for text strings is almost universally a bad idea in the age of unicode.

**Comment by MaxGraey** [comment]
@rossberg 
It still useful for `utf-16` comparison `wcscmp` in C. Most program written on C++ use `std::string` or `std::wstring`. Also have got other languages like AssemblyScript which use only `utf-16le` encoded strings.

**Comment by MaxGraey** [comment]
Got it. Closing for now
