### ISSUE TITLE
Description of memory.init doesn't match example

### ISSUE THREAD

**Issue by julian-seward1** [WebAssembly/bulk-memory-operations#22]
The description of memory.init says this

  The source segment and target memory are given as immediates. The instruction also has three i32 operands: [..]

The example in "Conditional Segment Initialization Example" only has one immediate:

    ;; copy data segment 1 into memory
    (memory.init 1
      (i32.const 0)     ;; source offset
      (i32.const 16)    ;; target offset
      (i32.const 7))    ;; length

I'm unclear if the inconsistency is intentional.  Does the memory-id default to zero if it is not specified?

**Comment by binji** [comment]
Yes, the target memory is 0 since only one imported or defined memory is allowed.

**Comment by lars-t-hansen** [comment]
The prose has been fixed (I don't know when it was fixed, but it carries a clarifying comment now).
