### ISSUE TITLE
Benchmarks include JS->wasm call?

### ISSUE THREAD

**Issue by sunfishcode** [WebAssembly/bulk-memory-operations#3]
On the [overview page](https://github.com/WebAssembly/bulk-memory-operations/blob/master/proposals/bulk-memory-operations/Overview.md), it describes the benchmark data as having this core loop:

```js
  let mask = Mib - 1;
  let start = performance.now();
  for (let i = 0; i < N; ++i) {
    f(dst_base + dst, src_base + src, size);
    dst = (dst + size) & mask;
    src = (src + size) & mask;
  }
  let end = performance.now();
```
This is JS, which suggests the benchmark includes JS calling wasm, which could have some overhead. I don't know the implementation details of the implementation from which you collected the data (which isn't specified), so I don't know how to interpret the results.

Could you clarify whether this is likely to be a concern?

**Comment by binji** [comment]
Yes, it definitely will have some overhead. The way I benchmarked it, it should have the same overhead both ways, though. I hacked V8 to look for any function called `_memcpy` or `_memmove` and replace it with a new function that just calls the `move_memory` instruction that I wrote. Then I compared the results between normal V8 and my hacked V8. I should probably add this info to the overview.

**Comment by binji** [comment]
Added some more info for the benchmark. Feel free to reopen if this is insufficient.
