### ISSUE TITLE
Reinterpreting memory indices as flags may not be backwards-compatible

### ISSUE THREAD

**Issue by alexcrichton** [WebAssembly/bulk-memory-operations#34]
Brought up in https://github.com/paritytech/parity-wasm/pull/227 at https://github.com/paritytech/parity-wasm/pull/227#discussion_r225211050, it was pointed out that currently the [data section today](http://webassembly.github.io/spec/core/binary/modules.html#binary-datasec) encodes a `memidx` at the start, which bottoms out as a u32 encoded as leb128. This means that it's possibly valid for the encoding to look like `0x80 0x00` instead of just `0x00` (and still be valid today). 

The current proposal here, though, assumes that all wasm files today which encode a zero index of memory do so canonically with a `0x00` byte. If an existing wasm module with the memory encoded as `0x80 0x00` is interpreted with this proposal I think it'll break because `0x80` isn't a valid set of bit flags?

Could today's `memidx: varuint32` field be reinterpreted as `flags: varuint32` to perhaps solve this? That way all existing modules with `flags: 0` would still be interpreted as memory index 0 and it'd also allow for extension with the flags proposed here too

**Comment by binji** [comment]
Yes, I see what you mean. I think making flags a variable length encoding fixes this.

**Comment by binji** [comment]
New spec test added here: https://github.com/WebAssembly/spec/pull/892
