### ISSUE TITLE
Bikeshedding the documentation: rename active/passive segments?

### ISSUE THREAD

**Issue by titzer** [WebAssembly/bulk-memory-operations#37]
Apologies if this has come up before. I was reading through the documentation and the names "active" and "passive" seem to bring a lot of connotations with them that might be confusing.

What if we dropped the term "passive" and renamed "active" segments to "autoload" (or perhaps "autoinit")?

**Comment by binji** [comment]
We had a little discussion about it before -- I think I originally called them "active" vs. "inactive". I don't care too much what we call them, but I think we do need some term for the segments that are what we currently call "passive".

I wouldn't like it very much if it ended up being "noautoinit" :-)

**Comment by binji** [comment]
We discussed this at the Nov 13 CG meeting, but nobody was very satisfied with the alternatives. Or perhaps they were all just tired of bikeshedding :-)
