### ISSUE TITLE
Split proposal into memory and table operations

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#47]
We discussed this at the Jan 22 CG meeting. Currently, the threads proposal depends on the bulk memory proposal. Passive element segments and `table.init` depend on the reference types proposal. The threads proposal doesn't really need passive element segments or the table instructions, however.

Should we split this proposal into separate parts for memory and table?

In the meeting, @littledan mentioned that, even if we do split this proposal, it may not be worth the effort to create a separate repository. Instead, it is more important to make sure browser compatibility documentation mentions this (on MDN, for example). This repository (and the overview) can mention this split as well.

**Comment by lars-t-hansen** [comment]
Since there are now three implementations (reference interpreter, v8, and SpiderMonkey) and nobody really worries about this any more, I'll close this.
