### ISSUE TITLE
`mem.clear` vs `mem.fill`

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#7]
This topic came up a [while ago](https://github.com/WebAssembly/design/issues/236#issuecomment-125700395), and again [later](https://github.com/WebAssembly/design/pull/1057).

We decided on `set_memory`/`memset`/`mem.fill`, but IMO this operation makes less sense when you look at the table equivalent, `table.fill`, since we currently have no good way to provide an immediate value.

Is it better to start with `mem.clear` and `table.clear` first, and add `mem.fill` later if desired?

**Comment by rossberg** [comment]
I kind of expect that we gonna have `table.get/set` in a similar timeframe, at which point `table.fill` would already work. So it may not be worth bothering with adding `clear` methods.

**Comment by lars-t-hansen** [comment]
With the reftypes proposal, table.clear == table.fill with ref.null even for table-of-funcref, and there is (as Andreas says) also table.get and table.set to complement that, for table-of-anyref.  If it becomes hard to spec table.fill here let's move it into reftypes.

**Comment by lars-t-hansen** [comment]
table.fill is coming with reference types (https://github.com/WebAssembly/reference-types/issues/14).
