### ISSUE TITLE
Is it a validation error to use memory.* if there is no memory?

### ISSUE THREAD

**Issue by tlively** [WebAssembly/bulk-memory-operations#79]
I didn't see this mentioned in overview.md.

**Comment by binji** [comment]
Yes, see https://github.com/WebAssembly/bulk-memory-operations/blob/master/document/core/valid/instructions.rst#memoryfill. It's not required for `data.drop`, though.

**Comment by lars-t-hansen** [comment]
> It's not required for `data.drop`, though.

On purpose or oversight?  Firefox will refuse to validate if data.drop is used without a memory, or elem.drop is used without a table; I can argue it both ways and I'm curious what people think.

**Comment by rossberg** [comment]
That makes sense to me. All memory ops reference memory index 0, but in the future may allow others, making the index explicit; `data.drop` OTOH does not have any memory index.

**Comment by tlively** [comment]
Thanks, all!
