### ISSUE TITLE
Clarification request for `memory.copy` and `memory.fill` argument meanings

### ISSUE THREAD

**Issue by julian-seward1** [WebAssembly/bulk-memory-operations#8]
(1) For `memory.fill`, all three arguments (destination address, value to set, and size of region) are stated as `i32`.

* For each argument individually: are these intended to be interpreted as signed or unsigned?

* For each argument individually: if the value is signed, what is the intended behaviour?
  - what does a negative address mean?
  - what value should be written if the fill value is negative?
  - what does a negative size mean?

* Is the destination address argument intended to be a byte offset into the memory region, or is there
some scaling of it?

* Is there any advantage to changing the address argument's type from `i32` to `memarg` as with other memory instructions?

(2) The exact same questions as in (1), but for `memory.copy`.

**Comment by binji** [comment]
Good questions.

> For each argument individually: if the value is signed, what is the intended behaviour?

The address would be the same as other memory addresses, so unsigned. The size of the region would be unsigned too, since a negative size is not useful. A signed value is not special, it will be truncated to `u8`, similar to the `i32.store8` instruction.

> Is the destination address argument intended to be a byte offset into the memory region, or is there
some scaling of it?

Byte offset, although there was discussion of only allowing page-size increments. If we did, that would be the scale factor.

> Is there any advantage to changing the address argument's type from i32 to memarg as with other memory instructions?

The benefit of using `memarg` is being able to provide a constant offset. I imagine that won't be as useful for `memory.fill` and `memory.copy`. If you have some concrete examples, that would be helpful though.

> The exact same questions as in (1), but for memory.copy

`memory.copy` should be consistent with `memory.fill`. If we choose to use page size increments, then all operations should do so. And negative addresses+sizes never make sense, I believe.

**Comment by julian-seward1** [comment]
Thanks for the clarifications.

>> Is there any advantage to changing the address argument's type from i32 to memarg [..]

> If you have some concrete examples, that would be helpful though.

I have no examples; I can't see how it would be helpful.  But I thought it worth checking.

**Comment by lars-t-hansen** [comment]
> > Is there any advantage to changing the address argument's type from i32 to memarg as with other memory instructions?
> 
> The benefit of using memarg is being able to provide a constant offset. I imagine that won't be as useful for memory.fill and memory.copy. If you have some concrete examples, that would be helpful though.

What about being able to talk about which memory we're using?  (Or for copy, which memories?)

**Comment by julian-seward1** [comment]
@binji: when it comes time to allow WebAssembly with multiple memory indices, how should this be incorporated?  For the "normal" memory instruction (loads, stores, etc) I guess a `memidx` could be added to `memarg`.  But here, we don't really want to have `memarg`s for the addresses since (as discussed above) there's no advantage in having a base+offset construction for the addresses.  So perhaps `memory.fill` should carry one `memidx` and `memory.copy` should carry two?

**Comment by julian-seward1** [comment]
Similarly, should `memory.copy` and `memory.fill` (and perhaps others) carry, respectively, 1 or 2 alignment hints for the base address(es)?  What about alignment hints for the lengths?

For a copy operation, could we have a hint which says "source and destination do not overlap"?  This would allow eliding a run-time direction check and, in an inlined case, one of the two copy-from-lowest-addresses-first or copy-highest-addresses-first blocks of code.  It would also facilitate using hardware instructions that directly allocate and zero the destination cache lines (eg POWER dcbz) rather than pointlessly loading them with old data from main memory, only to have it immediately overwritten.

**Comment by lukewagner** [comment]
Ensuring that `mem.copy`/`mem.set` work with multiple memories is necessary.  The current plan for loads/stores, to ensure backcompat, was to turn the `align` field into `alignAndFlags`, with a bit (past the last possible alignment bit) to say "an additional memory index immediate is present".  Other ops (`mem.grow`) simply have a currently-always-zero memory index immediate.

So should `memarg` be used or just plain memory indices?  If we think of the constant-small-index case as a small sequence of scalar loads/stores, then it seems like both `align` and `offset` would be useful for the same reason they are present on scalar loads/stores, so I think "yes".

> For a copy operation, could we have a hint which says "source and destination do not overlap"? This would allow eliding a run-time direction check and, in an inlined case, one of the two copy-from-lowest-addresses-first or copy-highest-addresses-first blocks of code.

In general wasm tries very hard to be portable (even when the wasm producer has incorrect hints), so I don't think a non-overlapping hint would allow us to elide any branches since we have to have the specified `memmove` behavior in all cases.  So that does mean a branch in the non-inline case.  I was thinking, for the inline case, we'd emit:
```
tmp1 = *(src)
tmp2 = *(src + K)
tmp3 = *(src + 2*K)
...
*(dst) = tmp1
*(dst + K) = tmp2
*(dst + 2*K) = tmp3
...
```
Looking at clang, this is indeed what `memmove` emits up to sizes of 128 (256 with `-mavx`) since it can use `%xmm`/`%ymm` regs and there are lots of those.  Past 128/256, clang calls out to libc (even though it has more regs available), presumably to balance code size.

**Comment by binji** [comment]
> So should memarg be used or just plain memory indices? If we think of the constant-small-index case as a small sequence of scalar loads/stores, then it seems like both align and offset would be useful for the same reason they are present on scalar loads/stores, so I think "yes".

Yes, I suppose I was a bit hasty. The offset allows you to access a pointer to a struct member without having to manually add the constant offset in, and it seems like that would be useful for the bulk `mem` operations too.

**Comment by jfbastien** [comment]
Is it proposed that copy be able to specify different memories for both source and destination?

**Comment by julian-seward1** [comment]
> Is it proposed that copy be able to specify different memories for both source and destination?

It sounds reasonable to me.  If it isn't allowed then we would have a situation where copying within a single memory would be much faster than copying across memories.  Which sounds undesirable.

**Comment by binji** [comment]
Agreed it seems reasonable, but regardless we can defer the decision until we have multiple memories. For now, we'll can have the two `memarg`s, and if we add multiple memories we can do the trick with the `align` @lukewagner describes above to extend them.

**Comment by jfbastien** [comment]
At that point do we also want embedder copy in / out? Probably as a separate function, I'm thinking something akin to Linux `copy_from_user`. Say in a JS embedding copying to / from strings and ArrayBuffers. In a native embedding copying from a `std::vector` or an array.

Of course, we have to make sure it's not a hole in our capabilities approach, and that all such copying is opt-in as well as bounds-checked.

**Comment by lukewagner** [comment]
I think something analogous to `copy_from_user` would be implemented either (1) host-side (as an importable function that can be called from wasm, passing an `i32` tuple `(begin, length)`, (2) as a host binding (annotating an import) if we need to Optimize Harder.

**Comment by rossberg** [comment]
I would prefer not to overload these operators by also adding memargs (two of them for copy?) -- for one, they are already complex enough, and moreover, that would divorce them from the analogous operators for tables.

**Comment by lukewagner** [comment]
The memory-index is absolutely necessary, align is semantically ignored, so is your only objection to the `offset`?

**Comment by rossberg** [comment]
Well, yes, e.g. in the case of copy it adds up to 9 parameters by my count (2 of which are ignored). I agree that the indices are necessary, but by only adding them we could at least keep it at 5. And maintain consistency between memories and tables.

**Comment by jfbastien** [comment]
But inconsistency with load and store? 🤔

**Comment by julian-seward1** [comment]
The question of whether to use `offset` in both `memory.*` and the basic load/store instructions seems to me ultimately to be an issue about where instruction selection is performed.  By forcing loads/stores to have an `offset`, we offload a small part of the instruction selection work (effective-address generation) to the front end (Wasm generator).  On the whole that's probably a good thing from from a startup-time perspective, because that's work that the JITs don't need to perform, and it also produces shorter Wasm code.  But it does pre-make code-quality decisions which may be suboptimal and need to be undone by the JITs, eg:

* ARM NEON load/store insns don't allow an immediate offset.  So we'd be forced to synthesise the value in register anyway.

* The immediate is too large to fit in a target instruction.  More general case of the above.

* I can see it complicating optimising back ends.  Imagine the Wasm creates some value `A=X+100` on the stack, and then issues loads at `A+offset=200` and `A+offset=300`.  In order to remove the redundant computation `X+100` and instead directly issue loads at `A+offset=300` and `A+offset=400`, an optimising back end is going to have to round up all the relevant offsets, possibly having to perform some analysis of the form "`Value1` and `Value2` differ by `const`" along the way.

There's also a slippery-slope effect.  Imagine in future there's a proposal to extend the Wasm `memarg` to be of the form `value1 + value2 << {0,1,2,3}`.  Should we take that step?  Will it exacerbate the above problems?

Personally I would prefer not to have `offset`s for `memory.{fill,copy}` for the above reasons.  But I don't think it's terribly important either way (here) and I'm not leaning heavily in either direction.

**Comment by jfbastien** [comment]
One argument for having offset is: if we have chains of stores (say to initialize a struct), and a part can be a memset, then we'd need to reify the base+offset into a temporary instead of the store base + offset that all the stores have.

One against: base+offset arithmetic don't wrap, so you can go off the end of 4GiB and engines need to be careful about that. With arbitrarily wide memops (which these are) we'd need more care.

**Comment by binji** [comment]
It seems that we don't really have enough information to make this decision. We could try to do some research, but ultimately that will be easier when we have the instruction in real wasm engines to test. The built-in offset is a nice-to-have, but not essential to having a fast copy or fill. So maybe it would be best to leave a reserved zero byte (or two) for now, and revisit later.

**Comment by julian-seward1** [comment]
@lukewagner, re comment of 22 Mar

>>   For a copy operation, could we have a hint which says "source and destination do not overlap"? This would allow eliding a run-time direction check and, in an inlined case, one of the two copy-from-lowest-addresses-first or copy-highest-addresses-first blocks of code.

> In general wasm tries very hard to be portable (even when the wasm producer has incorrect hints), so I don't think a non-overlapping hint would allow us to elide any branches since we have to have the specified memmove behavior in all cases. [..]

Given that C++ or Rust (at least) compiled into Wasm might actually desire a high performance .copy implementation for the cases where the compiler knows -- via alias analysis, or whatever -- that source and destination do not overlap, it seems a shame to preclude the possibility of a branchless inlined implementation in all cases.  I see that hinting is useless because it's not verifiable -- at least, not enough to give consistent behaviour across implementations.

One limited idea I had is to represent a no-overlap variant not by `(dst-index, src-index, len)` but rather by `(dst-index, offset-relative-to-dst-index, len)`.  That would make it possible to identify, at JIT time, cases where source and destination have a known offset, they don't overlap, and the length is a small constant.  Hence it would be possible to do branchless copies between different offsets on the stack or different offsets in the same (C++-heap) object.  Unfortunately it doesn't help for copies between different objects since the offset won't be a constant.

**Comment by lars-t-hansen** [comment]
Right now we have a reserved zero byte for both memory and table instructions.  It is possible to turn this into a raw index (we've done this for the reftypes proposal but that ship has not sailed) or a flag byte, if we want offsets etc.
