### ISSUE TITLE
Tests for passive element segments contain type

### ISSUE THREAD

**Issue by gahaas** [WebAssembly/bulk-memory-operations#89]
In the spec tests, the definition of passive element segments contains a type. However, this type is mentioned, neither in the Binary Format section nor in the Validation section. Are the spec tests or the spec more up to date?

**Comment by binji** [comment]
The tests are more up-to-date. I've updated the spec here: https://github.com/WebAssembly/bulk-memory-operations/pull/90

**Comment by eqrion** [comment]
@binji Can this be closed?
