### ISSUE TITLE
Simplify copy-direction check

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#96]
We discussed this at the 2019 June CG meeting, and decided to use a simpler check for determining the direction of the copy (for `memory.copy` and `table.copy`).

See https://github.com/WebAssembly/meetings/blob/master/2019/CG-06.md#possibly-simplify-runtime-conditions-for-copy-direction-discussion-and-for-oob-checks.

**Comment by rossberg** [comment]
This was done.
