### ISSUE TITLE
Allow zero-byte copy to be out-of-bounds

### ISSUE THREAD

**Issue by binji** [WebAssembly/bulk-memory-operations#97]
We discussed this at the 2019 June meeting and decided to allow (i.e. not trap on) zero bytes copies that are out-of-bounds.

See https://github.com/WebAssembly/meetings/blob/master/2019/CG-06.md#possibly-simplify-runtime-conditions-for-copy-direction-discussion-and-for-oob-checks

**Comment by AndrewScheidecker** [comment]
Does this relaxation apply to all of the memory/table init/copy/fill instructions?
- `memory.init`
- `memory.copy`
- `memory.fill`
- `table.init`
- `table.copy`
- `table.fill`

**Comment by rossberg** [comment]
Yes, that's the idea.

**Comment by lars-t-hansen** [comment]
Presumably this applies also to the initialization behavior of active segments; the Overview and the spec interpreter both specify the behavior of active segments in terms of the new instructions.

It seems to me that the formal spec has not been updated in this regard and still does eager bounds checking for table/memory initialization from active segments.

**Comment by rossberg** [comment]
@lars-t-hansen, I agree. @binji, do you intend to update those as well?

**Comment by binji** [comment]
Yes, I was planning to. Though if someone wants to do it before I get to it, that's ok too!

**Comment by rossberg** [comment]
I think this was addressed by #100, #101, and #102.
